name: coloring_book_for_kids
description: Tiktok style coloring book.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-111.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_storage: ^11.2.2
  firebase_core: ^2.13.1
  shared_preferences: ^2.1.2
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true