// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmCqt9DZowcW5xNP5j9pDH2NldwLXkv4w',
    appId: '1:1055211733361:android:5978f4de0cf3d0727df6d0',
    messagingSenderId: '1055211733361',
    projectId: 'coloring-book-for-kids-5eb1d',
    storageBucket: 'coloring-book-for-kids-5eb1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIWSo8up2MxbkxsMvgUJeQocItZurzGmk',
    appId: '1:1055211733361:ios:82b4cab3d329dec77df6d0',
    messagingSenderId: '1055211733361',
    projectId: 'coloring-book-for-kids-5eb1d',
    storageBucket: 'coloring-book-for-kids-5eb1d.appspot.com',
    iosClientId: '1055211733361-hmo904tt01bd3k6tf0te85hf4i72frs9.apps.googleusercontent.com',
    iosBundleId: 'cz.jankubes.coloringbook.coloringBookForKids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIWSo8up2MxbkxsMvgUJeQocItZurzGmk',
    appId: '1:1055211733361:ios:2adca61b9e377adc7df6d0',
    messagingSenderId: '1055211733361',
    projectId: 'coloring-book-for-kids-5eb1d',
    storageBucket: 'coloring-book-for-kids-5eb1d.appspot.com',
    iosClientId: '1055211733361-vr1q3dt8h4tkft1s7oghvpn5cg1fv934.apps.googleusercontent.com',
    iosBundleId: 'cz.jankubes.coloringbook.coloringBookForKids.RunnerTests',
  );
}
